remote_theme: thelehhman/texture
title: Josefina Dalla Via Monti
author: GitHub User
email: josefinadallavia@gmail.com
description: > # this means to ignore newlines until "show_exerpts:"
  Josefina Dalla Via Monti's Personal website.
show_excerpts: true # set to true to show excerpts on the homepage
#baseurl: /texture
presentation: coding-post

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass

permalink: /posts/:title/
texture:
  title: Josefina Dalla Via Monti
  tagline: Data Scientist. MSc in Business Analytics.
  date_format: "%b %-d, %Y"
  style: blue
  showNav: true
  showPicker: false
  navigation:
      - title: Home
        url: "/posts/presentation"
      - title: My Work
        url: "/posts/my-work"
      - title: Resume
        url: "/posts/resume"


  # generate social links in footer
  social_links:
    twitter: josedallavia
    github:  josedallavia
    linkedIn: in/josefina-dalla-via-monti-22203772
    rss: rss
 

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up


# Build settings
# theme: texture

plugins:
  - jekyll-seo-tag
#  - jekyll-feed